#!/bin/sh

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#8AB4F8cc'  # default
T='#ffffffee'  # text
W='#d93025bb'  # wrong
V='#80cbc4bb'  # verifying

i3lock \
--insidever-color=$C   \
--ringver-color=$V     \
\
--insidewrong-color=$C \
--ringwrong-color=$W   \
\
--inside-color=$B      \
--ring-color=$D        \
--line-color=$B        \
--separator-color=$D   \
\
--verif-color=$T        \
--wrong-color=$T        \
--time-color=$T        \
--date-color=$T        \
--layout-color=$T      \
--keyhl-color=$T       \
--bshl-color=$W        \
\
--screen 1            \
--blur 10             \
--clock               \
--indicator           \
--time-str="%H:%M:%S"  \
--date-str="%A, %m %Y" \
--keylayout 1         \
--pass-media-keys     \
--pass-screen-keys    \
--lock-text="bloqueando..." \
--verif-text="verificando..." \
--wrong-text="não foi dessa vez!" \
--lockfailed-text="bloqueio falhou!" \
--noinput-text="vazio" \
--time-font=FiraSans-UltraLight \
--date-font=FiraSans-Light \
--layout-font=FiraSans-Light \
--verif-font=FiraSans-Light \
--wrong-font=FiraSans-Light \
--greeter-font=FiraSans-Light \
--time-size=38 \
--date-size=16 \
--layout-size=9 \
--verif-size=16 \
--wrong-size=16 \
--greeter-size=16 \
"$@"

