# Monitors
# ref: https://wiki.hypr.land/Configuring/Monitors/
# monitor = name, disable
# monitor = name, resolution, pos, scale #optional:#, mirror, name, transform, X
$hdmi_res = 1920x1080@75
$dp_res = 1920x1080@60

# Display control script
exec-once = $scrpath/monitor.sh -h $hdmi_res -d $dp_res #--external-only

monitor= , preferred, auto, auto

#monitor = HDMI-A-1, 1920x1080@60, 0x0, 1
monitor = HDMI-A-1, $hdmi_res, 0x0, 1
#monitor = eDP-1, disable
monitor = eDP-1, $dp_res, 1920x0, 1, # mirror, DP-1
