add_newline = false

[directory]
truncation_length = 1

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style)[·](purple) )'

[character]
vicmd_symbol = "[❯](bold purple)"

[cmd_duration]
format = "[$duration]($style) "

[line_break]
disabled = true
