#!/usr/bin/env bash

paru -S --needed --noconfirm fcitx5 fcitx5-mozc fcitx5-rime fcitx5-configtool

git clone https://github.com/catppuccin/fcitx5.git /tmp/catppuccin-fcitx5
mkdir -p ~/.local/share/fcitx5/themes/
cp -r /tmp/catppuccin-fcitx5/src/* ~/.local/share/fcitx5/themes

