-- ref: https://wiki.hypr.land/Configuring/Keywords/
-- Keycodes: https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon-keysyms.h

local s = require('lua.settings')
local mod = s.mod
local config = os.getenv("XDG_CONFIG_HOME") or ((os.getenv("HOME") or "") .. "/.config")

-- Launch
hl.bind(mod .. " + Return", hl.dsp.exec_cmd(s.terminal), { submap_universal = true })
hl.bind("CONTROL + ALT + t", hl.dsp.exec_cmd("kitty"), { submap_universal = true })
hl.bind(mod .. " + e", hl.dsp.exec_cmd(s.file_manager), { submap_universal = true })
hl.bind(mod .. " + d", hl.dsp.exec_cmd("pkill -x " .. s.menu .." || " .. s.menu .. ' ' .. s.launch),
	{ submap_universal = true })
hl.bind(mod .. " + g", hl.dsp.exec_cmd("pkill -x " .. s.menu .. " || " .. s.menu .. ' ' .. s.clients),
	{ submap_universal = true })
hl.bind(mod .. " + y", hl.dsp.exec_cmd("pkill -x " .. s.menu .. " || " .. s.network),
	{ submap_universal = true })
hl.bind("ALT + Tab", hl.dsp.exec_cmd(s.alt_tab))
hl.bind("ALT + SHIFT + Tab", hl.dsp.exec_cmd(s.alt_tab))
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mod .. " + i", hl.dsp.exec_cmd(s.editor), { submap_universal = true })
hl.bind(mod .. " + u", hl.dsp.exec_cmd(s.document_reader), { submap_universal = true })
hl.bind(mod .. " + SHIFT + F", hl.dsp.exec_cmd(s.browser), { submap_universal = true })
hl.bind(mod .. " + SHIFT + M", hl.dsp.exec_cmd(s.email_client), { submap_universal = true })
hl.bind(mod .. " + ALT + t", hl.dsp.exec_cmd(s.popin_terminal))
hl.bind("CONTROL + SHIFT + Escape", hl.dsp.exec_cmd(s.sys_monitor))
hl.bind("ALT + SHIFT + Escape", hl.dsp.exec_cmd(s.gpu_monitor))
hl.bind("CONTROL + ALT + Delete", hl.dsp.exec_cmd(s.sys_monitor))
hl.bind(mod .. " + Escape", hl.dsp.exec_cmd("hyprlock"), { submap_universal = true })
hl.bind("ALT + F2", hl.dsp.exec_cmd("pkill -x " .. s.menu .. " || " .. s.menu .. " -show run"))
hl.bind(mod .. " + SHIFT + P", hl.dsp.exec_cmd("hyprpicker -an"), { submap_universal = true })
hl.bind(mod .. " + ALT + n", hl.dsp.exec_cmd(s.scrpath .. "/wallpaper.sh --next"), { submap_universal = true })
hl.bind(mod .. " + m", hl.dsp.exec_cmd("makoctl restore"))
hl.bind(mod .. " + ALT + Return", hl.dsp.exec_cmd("makoctl invoke confirm"))
hl.bind(mod .. " + CONTROL + m", hl.dsp.exec_cmd("makoctl menu -- rofi -dmenu -p mako"))
hl.bind(mod .. " + ALT + m", hl.dsp.exec_cmd("makoctl dismiss -a"))
hl.bind(mod .. " + F12", hl.dsp.exec_cmd(config .. "/waybar/scripts/bluelight.sh -n"))
hl.bind(mod .. " + v", hl.dsp.exec_cmd("rofi -modi clipboard:" .. config .. "/rofi/scripts/clipvault.sh" .. " -show clipboard -show-icons"))

-- ref: https://wiki.hypr.land/Configuring/Binds/
hl.bind(mod .. " + Delete", hl.dsp.exec_cmd("wlogout"))
hl.bind(mod .. " + CONTROL + Delete", hl.dsp.exit(), { locked = true })
hl.bind(mod .. " + q", hl.dsp.window.close())
hl.bind(mod .. " + c", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + t", hl.dsp.window.pin())
hl.bind(mod .. " + p", hl.dsp.window.pseudo())
hl.bind(mod .. " + o", hl.dsp.layout("togglesplit"))
hl.bind(mod .. " + s", hl.dsp.group.toggle())
hl.bind(mod .. " + f", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind("ALT + Return", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + SHIFT + S", hl.dsp.exec_cmd(s.screenshot))
hl.bind(mod .. " + Print", hl.dsp.exec_cmd(s.screenshot_all))
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m output -m active -o " .. s.screenshots_dir .. " -f " .. s.screenshots_format))
hl.bind("SUPER + F11", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("ALT + F4", hl.dsp.window.kill())

-- Move focus with leader + arrow keys
hl.bind(mod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + SHIFT + H", hl.dsp.window.move({ into_or_create_group = "l" }))
hl.bind(mod .. " + SHIFT + L", hl.dsp.window.move({ into_or_create_group = "r" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ into_or_create_group = "u" }))
hl.bind(mod .. " + SHIFT + J", hl.dsp.window.move({ into_or_create_group = "d" }))
hl.bind(mod .. " + ALT + h", hl.dsp.group.prev())
hl.bind(mod .. " + ALT + l", hl.dsp.group.next())
hl.bind(mod .. " + ALT + j", hl.dsp.focus({ monitor = "+1" }))
hl.bind(mod .. " + ALT + k", hl.dsp.focus({ monitor = -1 }))
hl.bind(mod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + ALT + left", hl.dsp.group.prev())
hl.bind(mod .. " + ALT + right", hl.dsp.group.next())
hl.bind(mod .. " + ALT + up", hl.dsp.focus({ monitor = "+1" }))
hl.bind(mod .. " + ALT + down", hl.dsp.focus({ monitor = -1 }))
--bind = s.mod, Tab, cyclenext         # Change focus to another window
hl.bind(mod .. " + hiragana_katakana", hl.dsp.window.cycle_next({ next = true } --[[ cyclenext: unrecognized arg(s) "hist" ]]))
hl.bind(mod .. " + hiragana_katakana", hl.dsp.window.alter_zorder({ mode = "top" }))
hl.bind(mod .. " + hiragana_katakana", hl.dsp.window.fullscreen_state({ internal = 0, client = -1, action = "toggle" }))
hl.bind("ALT + hiragana_katakana", hl.dsp.window.cycle_next({ next = true }))
hl.bind("ALT + hiragana_katakana", hl.dsp.window.alter_zorder({ mode = "top" }))
--bind = s.mod, apostrophe, fullscreenstate, 0 -1
hl.bind("ALT + apostrophe", hl.dsp.group.next(), { non_consuming = true })
hl.bind(mod .. " + SHIFT + hiragana_katakana", hl.dsp.window.cycle_next({ prev = true }))
hl.bind(mod .. " + SHIFT + hiragana_katakana", hl.dsp.window.bring_to_top())

-- Resize windows
hl.bind(mod .. " + SHIFT + right", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
hl.bind(mod .. " + SHIFT + left", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
hl.bind(mod .. " + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
hl.bind(mod .. " + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })
hl.bind(mod .. " + SHIFT + period", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
hl.bind(mod .. " + SHIFT + comma", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
hl.bind(mod .. " + SHIFT + minus", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
hl.bind(mod .. " + SHIFT + equal", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })

-- Scrolling Layout
hl.bind(mod .. " + r", hl.dsp.layout("colresize +conf"), { repeating = true })
hl.bind(mod .. " + SHIFT + r", hl.dsp.layout("colresize -conf"), { repeating = true })

-- Switch workspaces with leader + [0-9]
hl.bind(mod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mod .. " + CONTROL + Right", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mod .. " + CONTROL + Left", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mod .. " + CONTROL + Down", hl.dsp.focus({ monitor = "+1" }))
hl.bind(mod .. " + CONTROL + Up", hl.dsp.focus({ monitor = -1 }))
hl.bind(mod .. " + CONTROL + l", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mod .. " + CONTROL + h", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mod .. " + n", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + N", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CONTROL + j", hl.dsp.window.move({ monitor = "+1" }))
hl.bind(mod .. " + CONTROL + k", hl.dsp.window.move({ monitor = "-1" }))
hl.bind(mod .. " + CONTROL + SHIFT + L", hl.dsp.window.move({ workspace = "r+1" }))
hl.bind(mod .. " + CONTROL + SHIFT + H", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind(mod .. " + CONTROL + SHIFT + J", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "+1" })) end)
hl.bind(mod .. " + CONTROL + SHIFT + K", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = -1 })) end)
hl.bind(mod .. " + CONTROL + o", hl.dsp.workspace.swap_monitors({ monitor1 = "0", monitor2 = "1" }))
hl.bind(mod .. " + CONTROL + Tab", hl.dsp.workspace.swap_monitors({ monitor1 = "0", monitor2 = "1" }))

-- Move active window to a workspace with leader + SHIFT + [0-9]
hl.bind(mod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind(mod .. " + ALT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mod .. " + ALT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mod .. " + ALT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mod .. " + ALT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mod .. " + ALT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mod .. " + ALT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mod .. " + ALT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mod .. " + ALT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mod .. " + ALT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mod .. " + ALT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

-- Hidden workspace / minimize window
hl.bind(mod .. " + a", hl.dsp.workspace.toggle_special("hidden"))
hl.bind(mod .. " + comma", hl.dsp.window.move({ workspace = "special:hidden", follow = false }))
hl.bind(mod .. " + comma", hl.dsp.window.move({ workspace = "+0" }))

-- Scroll through existing workspaces with leader + scroll
hl.bind(mod .. " + mouse_up", hl.dsp.window.cycle_next({ prev = true }))
hl.bind(mod .. " + mouse_up", hl.dsp.window.alter_zorder({ mode = "top" }))
hl.bind(mod .. " + mouse_down", hl.dsp.window.cycle_next({ next = true }))
hl.bind(mod .. " + mouse_down", hl.dsp.window.alter_zorder({ mode = "top" }))
hl.bind(mod .. " + CONTROL + mouse_up", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + CONTROL + mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CONTROL + SHIFT + mouse_down", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "+1" })) end)
hl.bind(mod .. " + CONTROL + SHIFT + mouse_up", function() local w = hl.get_active_workspace(); if not w then return end; hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = -1 })) end)

-- Submap
hl.bind(mod .. " + w", hl.dsp.submap("move"))
hl.define_submap("move", function()
    hl.bind("Escape", hl.dsp.submap("reset"))
    hl.bind("Space", hl.dsp.submap("reset"))
    hl.bind("CONTROL + c", hl.dsp.submap("reset"))
    hl.bind("CONTROL + bracketleft", hl.dsp.submap("reset"))
    hl.bind("a", hl.dsp.submap("reset"))
    hl.bind("i", hl.dsp.submap("reset"))
    hl.bind("o", hl.dsp.layout("togglesplit"))
    hl.bind("s", hl.dsp.group.toggle())
    hl.bind(mod .. " + s", hl.dsp.group.toggle())
    hl.bind(mod .. " + o", hl.dsp.layout("togglesplit"))
    hl.bind(mod .. " + h", hl.dsp.focus({ direction = "left" }))
    hl.bind(mod .. " + l", hl.dsp.focus({ direction = "right" }))
    hl.bind(mod .. " + k", hl.dsp.focus({ direction = "up" }))
    hl.bind(mod .. " + j", hl.dsp.focus({ direction = "down" }))
    hl.bind("ALT + h", hl.dsp.window.swap({ direction = "l" }))
    hl.bind("ALT + l", hl.dsp.window.swap({ direction = "r" }))
    hl.bind("ALT + k", hl.dsp.window.swap({ direction = "u" }))
    hl.bind("ALT + j", hl.dsp.window.swap({ direction = "d" }))
    hl.bind("h", hl.dsp.window.move({ into_or_create_group = "l" }))
    hl.bind("l", hl.dsp.window.move({ into_or_create_group = "r" }))
    hl.bind("k", hl.dsp.window.move({ into_or_create_group = "u" }))
    hl.bind("j", hl.dsp.window.move({ into_or_create_group = "d" }))
    hl.bind("SHIFT + H", hl.dsp.window.move({ into_group = "l" }))
    hl.bind("SHIFT + L", hl.dsp.window.move({ into_group = "r" }))
    hl.bind("SHIFT + K", hl.dsp.window.move({ into_group = "u" }))
    hl.bind("SHIFT + J", hl.dsp.window.move({ into_group = "d" }))
    hl.bind("right", hl.dsp.window.move({ into_or_create_group = "l" }))
    hl.bind("left", hl.dsp.window.move({ into_or_create_group = "r" }))
    hl.bind("up", hl.dsp.window.move({ into_or_create_group = "u" }))
    hl.bind("down", hl.dsp.window.move({ into_or_create_group = "d" }))
    hl.bind("1", hl.dsp.focus({ workspace = 1 }))
    hl.bind("2", hl.dsp.focus({ workspace = 2 }))
    hl.bind("3", hl.dsp.focus({ workspace = 3 }))
    hl.bind("4", hl.dsp.focus({ workspace = 4 }))
    hl.bind("5", hl.dsp.focus({ workspace = 5 }))
    hl.bind("6", hl.dsp.focus({ workspace = 6 }))
    hl.bind("7", hl.dsp.focus({ workspace = 7 }))
    hl.bind("8", hl.dsp.focus({ workspace = 8 }))
    hl.bind("9", hl.dsp.focus({ workspace = 9 }))
    hl.bind("0", hl.dsp.focus({ workspace = 10 }))
    hl.bind(mod .. " + 1", hl.dsp.focus({ workspace = 1, on_current_monitor = true }))
    hl.bind(mod .. " + 2", hl.dsp.focus({ workspace = 2, on_current_monitor = true }))
    hl.bind(mod .. " + 3", hl.dsp.focus({ workspace = 3, on_current_monitor = true }))
    hl.bind(mod .. " + 4", hl.dsp.focus({ workspace = 4, on_current_monitor = true }))
    hl.bind(mod .. " + 5", hl.dsp.focus({ workspace = 5, on_current_monitor = true }))
    hl.bind(mod .. " + 6", hl.dsp.focus({ workspace = 6, on_current_monitor = true }))
    hl.bind(mod .. " + 7", hl.dsp.focus({ workspace = 7, on_current_monitor = true }))
    hl.bind(mod .. " + 8", hl.dsp.focus({ workspace = 8, on_current_monitor = true }))
    hl.bind(mod .. " + 9", hl.dsp.focus({ workspace = 9, on_current_monitor = true }))
    hl.bind(mod .. " + 0", hl.dsp.focus({ workspace = 10, on_current_monitor = true }))
    hl.bind("SHIFT + period", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + comma", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + minus", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
    hl.bind("SHIFT + equal", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })
    hl.bind("SHIFT + right", hl.dsp.window.resize({ x = 30, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + left", hl.dsp.window.resize({ x = -30, y = 0, relative = true }), { repeating = true })
    hl.bind("SHIFT + up", hl.dsp.window.resize({ x = 0, y = -30, relative = true }), { repeating = true })
    hl.bind("SHIFT + down", hl.dsp.window.resize({ x = 0, y = 30, relative = true }), { repeating = true })
end)

hl.bind("ALT + Tab", hl.dsp.submap("select"))
hl.bind("ALT + SHIFT + Tab", hl.dsp.submap("select"))
hl.define_submap("select", function()
    hl.bind("ALT + Tab", hl.dsp.send_shortcut({ mods = "", key = "Tab", window = "" }))
    hl.bind("ALT + SHIFT + Tab", hl.dsp.send_shortcut({ mods = "Shift", key = "Tab", window = "" }))
    hl.bind("Escape", hl.dsp.send_shortcut({ mods = "", key = "Escape", window = "" }))
    hl.bind("ALT + Escape", hl.dsp.send_shortcut({ mods = "", key = "Escape", window = "" }))
    hl.bind("ALT + Escape", hl.dsp.submap("reset"))
    hl.bind("Space", hl.dsp.send_shortcut({ mods = "", key = "Space", window = "" }))
    hl.bind("Space", hl.dsp.submap("reset"))
    -- bindrt = Alt, Alt_L, exec, pkill -x s.menu || s.menu s.launch 
    hl.bind("ALT + Alt_L", hl.dsp.send_shortcut({ mods = "", key = "Return", window = "" }), { release = true, transparent = true })
    hl.bind("ALT + Alt_L", hl.dsp.submap("reset"), { release = true, transparent = true })
    hl.bind("Escape", hl.dsp.submap("reset"))
    hl.bind("catchall", hl.dsp.submap("reset"), { non_consuming = true })
end)

-- Move/resize windows with leader + LMB/RMB and dragging
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Minimize/float window with leader + MMB/right
hl.bind(mod .. " + mouse:274", hl.dsp.window.move({ workspace = "special:hidden" }), { release = true, click = true })
hl.bind(mod .. " + mouse:272", hl.dsp.window.move({ workspace = "+0" }), { release = true, click = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.float({ action = "toggle" }), { release = true, click = true })

-- Zoom
hl.bind(mod .. " + SHIFT + mouse_down", hl.dsp.exec_cmd("hyprctl -q      keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j \t| jq '.float * 1.41421')"))
hl.bind(mod .. " + SHIFT + mouse_up", hl.dsp.exec_cmd("hyprctl -q        keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j \t| jq '(.float * 0.707107) | if . < 1 then 1 else . end')"))

hl.bind(mod .. " + CONTROL + equal", hl.dsp.exec_cmd("hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float * 1.41421')"), { repeating = true })
hl.bind(mod .. " + CONTROL + minus", hl.dsp.exec_cmd("hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '(.float * 0.707107) | if . < 1 then 1 else . end')"), { repeating = true })

hl.bind(mod .. " + CONTROL + mouse_up", hl.dsp.exec_cmd("hyprctl -q keyword cursor:zoom_factor 1"))
hl.bind(mod .. " + CONTROL + mouse_down", hl.dsp.exec_cmd("hyprctl -q keyword cursor:zoom_factor 1"))
hl.bind(mod .. " + SHIFT + minus", hl.dsp.exec_cmd("hyprctl -q keyword cursor:zoom_factor 1"))
hl.bind(mod .. " + CONTROL + 0", hl.dsp.exec_cmd("hyprctl -q keyword cursor:zoom_factor 1"))

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("CONTROL + XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Lid Open/Close event (For Laptop)
hl.bind("switch:Lid Switch", hl.dsp.exec_cmd("hyprlock"), { locked = true })
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd('hyprctl keyword monitor "eDP-1, disable"'), { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd('hyprctl keyword monitor "eDP-1, preferred, ' .. s.edp_pos .. ', 1"'), { locked = true })

-- Gestures
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})
hl.gesture({
    fingers = 3,
    direction = "down",
    action = function() hl.dsp.exec_cmd("pkill -x s.menu || s.menu s.launch") end,
})

