-- Input
-- https://wiki.hypr.land/Configuring/Variables/#input
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
    name = "logitech-g203-prodigy-gaming-mouse",
    sensitivity = 0,
    accel_profile = "flat",
})

hl.device({
    name = "syna7db5:01-06cb:cd41-touchpad",
    sensitivity = 0,
    natural_scroll = true,
    accel_profile = "custom 1.0 0.0 1.0 2.0 3.0 8.0 16.0 32.0",
})

hl.device({
    name = "syna312b:00-06cb:cfe2-touchpad",
    sensitivity = 0,
    natural_scroll = true,
    accel_profile = "custom 1.0 0.0 1.0 2.0 3.0 8.0 16.0 32.0",
})

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 1.00,
    bezier = "quick",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 1.00,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 1.00,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.00,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 0.50,
    bezier = "quick",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.50,
    bezier = "quick",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 2,
    bezier = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 2,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 2,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = false,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = false,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 5,
    bezier = "easeOutQuint",
})

hl.config({
    input = {
        kb_layout = "br,us",
        kb_variant = ",altgr-intl",
        kb_model = "pc105", -- abnt2 
        kb_options = "lv3:ralt_switch,compose:lctrl-altgr,grp:alt_space_toggle",
        kb_rules = "",
        numlock_by_default = true,
        follow_mouse = 1,
        follow_mouse_threshold = 150.0,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        accel_profile = "flat",
        touchpad = {
            natural_scroll = true,
        },
    },
    -- https://wiki.hypr.land/Configuring/Variables/#gestures
    gestures = {
        workspace_swipe_forever = true,
        workspace_swipe_direction_lock_threshold = 6,
    },
    -- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
    -- Look and Feel
    general = {
        gaps_in = 3,
        gaps_out = 6,
        border_size = 1,
        -- ref: https://wiki.hypr.land/Configuring/Variables/#variable-types
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        resize_on_border = true,
        extend_border_grab_area = 8,
        no_focus_fallback = true,
        -- ref: https://wiki.hypr.land/Configuring/Tearing/
        allow_tearing = false,
        layout = "dwindle",
    },
    decoration = {
        rounding = 8,
        rounding_power = 2,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = false,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    group = {
        auto_group = false,
        col = {
            border_active = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            border_inactive = "rgba(595959aa)",
        },
        groupbar = {
            font_size = 11,
            height = 1,
            rounding = 2,
            gaps_out = 0,
            keep_upper_gap = false,
            -- font_weight_active = medium
            render_titles = true,
            indicator_height = 16,
            text_offset = -8,
            col = {
                active = { colors = { "rgba(11111bee)", "rgba(1e1e2eee)" }, angle = 0 },
                inactive = "rgba(1e1e2eaa)",
            },
        },
    },
    -- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hypr.land/Configuring/Scrolling-Layout/ for more
    scrolling = {
        fullscreen_on_one_column = true,
        column_width = 1.0,
        direction = "right",
        explicit_column_widths = "0.333, 0.5, 0.75, 1.0",
    },
    -- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hypr.land/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering = true,
    },
    cursor = {
        persistent_warps = true,
        --no_warps = true
        warp_on_change_workspace = 1,
        --hide_on_key_press = true
        inactive_timeout = 2,
    },
    -- https://wiki.hypr.land/Configuring/Variables/#animations
    animations = {
        enabled = true,
        -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
    },
    binds = {
        drag_threshold = 10,
        movefocus_cycles_fullscreen = true,
        hide_special_on_workspace_change = true,
    },
})


